### ISSUE TITLE
I call hacks

### ISSUE THREAD

**Issue by PenetratingShot** [talonbragg/RainbowHover#1]
You copied most of this and then edited it to make it look like it was yours. Take a look at the code and commit history

**Comment by talonbragg** [comment]
This was originally a js fiddle that I made. You can see it yourself here:  [JSFIDDLE](https://jsfiddle.net/talon4567/xb8tfqk1/). I just put my code into this from there. JSFIDDLE is where I test my things.

**Comment by talonbragg** [comment]
Why do you keep going around and telling everybody that I copied it, I made it fully myself! Do you just think that it is too good and that I didn't make it because of that, it is fully mine and I have stated that many, many times!

**Comment by talonbragg** [comment]
Even if you think that I copied it, what is your proof?
